# https://taskfile.dev

version: '3'

vars:
  PROJECT_NAME: "Golden Point"
  VERSION: "1.2.14"

includes:
  build: Taskfile_{{OS}}.yml

tasks:
  default:
    cmds:
      - task: build:depend
      - task: build:generate
      - task: build:build
      - task: build:package
