# https://taskfile.dev

version: '3'

includes:
  build: ./Taskfile_{{OS}}.yml

tasks:
  default:
    cmds:
      - task: build:depend
      - task: build:prepare
      - task: build:build
      - task: build:package
