# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: depend
#      - task: check
      - task: prepare
      - task: build

  clean:
    cmds:
      - rm -rf ./package
      - rm -rf ./dist

  depend:
    cmds:
      - go get -v -u

  check:
    cmds:
      - go test ./...

  prepare:
    cmds:
#      - npm install -g less
      - cd contrib && lessc main.less main.css
      - cp contrib/main.css static/css/main.css

