version: 2
jobs:
  build:
    working_directory: /tmp/golden-1.2.3
    docker:
      - image: debian:10
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: Update Go depenedncies
          command: /bin/sh ./depend.sh
      - run:
          name: Check Golden point module compatibles
          command: /bin/sh ./check.sh
      - run:
          name: Build Golden Point Linux binnary package
          command: /bin/sh ./build.sh
      - run:
          name: Create binnary package distribution
          command: /bin/sh ./package.sh
      - store_artifacts:
          path: /tmp/golden-1.2.3/dist
          destination: raw-test-output
