version: 2
jobs:
  build:
    working_directory: /tmp/golden-1.2.3
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: Check Golden point modle compatible
          command: go test .
      - run:
          name: Build Golden Point Linux binnary package
          command: go build .
      - run:
          name: Create binnary package distribution
          command: /bin/sh ./package.sh
      - store_artifacts:
          path: /opt/golden-1.2.3/*.deb
          destination: raw-test-output
