name: Go
on: [push]
jobs:

  build-win32:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install Golang module dependencies
        run: go get -v -t -d ./...
      - name: Check
        run: go test -v ./...
      - name: Build
        run: |
          GOOS=windows GOARCH=386 CGO_ENABLED=1 go build -o golden-win32-i386.exe .
          GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build -o golden-win32-amd64.exe .

  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install Golang module dependencies
        run: go get -v -t -d ./...
      - name: Check
        run: go test -v ./...
      - name: Build
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o golden-linux-amd64.exe .
