name: Go
on: [push]
jobs:

  build-win32:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '3.x'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Make build
        run: task

  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '3.x'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Make build
        run: task

  build-macos:
    name: Build on macOS X
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '3.x'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Make build
        run: task

